### ISSUE TITLE
Client = Player 1 does not start

### ISSUE THREAD

**Issue by titanic1234** [FalconsSky/socha-python-client#8] opened 2022-10-08 20:44 UTC
If the client is player 1, the game does not start because he does not make a move first.
![grafik](https://user-images.githubusercontent.com/93482292/194727094-0185cf80-d5f0-4f93-a602-39fd1348b45a.png)

**Comment by FalconsSky** [comment] 2022-10-08 21:16
Hi @titanic1234, 
thanks for the report.
I did reproduce the bug and will investigate the cause of it.

**Comment by FalconsSky** [comment] 2022-10-08 22:21
The issue should be resolved with #9 and v0.9.6.
Remember to update the package with `pip install socha -U`.

**Closed by FalconsSky** 2022-10-08 22:21 UTC
Labels: bug
